# Windows PowerShell deployment helper script
# Run this from your LOCAL machine to help with deployment tasks

param(
    [Parameter(Mandatory=$false)]
    [string]$ServerIP = "",
    
    [Parameter(Mandatory=$false)]
    [ValidateSet("test", "setup-env", "upload-code", "help")]
    [string]$Action = "help"
)

$ErrorActionPreference = "Stop"

function Show-Help {
    Write-Host @"
CRM Backend Deployment Helper (Windows)
========================================

Usage: .\deploy-windows.ps1 -ServerIP YOUR_SERVER_IP -Action <action>

Actions:
  test          Test connection to your deployed backend
  setup-env     Create frontend .env.local file with server IP
  upload-code   Upload backend code to server via SCP (use with caution)
  help          Show this help message

Examples:
  .\deploy-windows.ps1 -ServerIP 123.45.67.89 -Action test
  .\deploy-windows.ps1 -ServerIP 123.45.67.89 -Action setup-env

Note: SSH connection must be done manually. This script helps with common tasks.
"@
}

function Test-Backend {
    param([string]$IP)
    
    Write-Host "🔍 Testing backend at http://$IP..." -ForegroundColor Blue
    
    try {
        # Test health endpoint
        $response = Invoke-WebRequest -Uri "http://$IP/health" -UseBasicParsing -TimeoutSec 10
        $content = $response.Content | ConvertFrom-Json
        
        Write-Host "✅ Backend is healthy!" -ForegroundColor Green
        Write-Host "Status: $($content.status)"
        Write-Host "Agent initialized: $($content.agent_initialized)"
        Write-Host "Gradium initialized: $($content.gradium_initialized)"
        
        # Test root endpoint
        $rootResponse = Invoke-WebRequest -Uri "http://$IP/" -UseBasicParsing -TimeoutSec 10
        Write-Host "✅ Root endpoint accessible" -ForegroundColor Green
        
        return $true
    }
    catch {
        Write-Host "❌ Backend test failed: $_" -ForegroundColor Red
        Write-Host ""
        Write-Host "Troubleshooting steps:" -ForegroundColor Yellow
        Write-Host "1. SSH into server: ssh root@$IP"
        Write-Host "2. Check backend status: sudo systemctl status crm-backend"
        Write-Host "3. Check logs: sudo journalctl -u crm-backend -f"
        Write-Host "4. Check firewall: sudo ufw status"
        return $false
    }
}

function Setup-FrontendEnv {
    param([string]$IP)
    
    Write-Host "📝 Setting up frontend .env.local file..." -ForegroundColor Blue
    
    $frontendDir = Join-Path $PSScriptRoot ".." "frontend"
    
    if (-not (Test-Path $frontendDir)) {
        Write-Host "❌ Frontend directory not found at: $frontendDir" -ForegroundColor Red
        return $false
    }
    
    $envPath = Join-Path $frontendDir ".env.local"
    
    $envContent = @"
# Backend API URL (auto-generated by deploy-windows.ps1)
NEXT_PUBLIC_API_URL=http://$IP
"@
    
    $envContent | Out-File -FilePath $envPath -Encoding utf8 -Force
    
    Write-Host "✅ Created $envPath" -ForegroundColor Green
    Write-Host ""
    Write-Host "File contents:"
    Get-Content $envPath | ForEach-Object { Write-Host "  $_" }
    Write-Host ""
    Write-Host "⚠️  Remember to restart your Next.js dev server!" -ForegroundColor Yellow
    
    return $true
}

function Upload-Code {
    param([string]$IP)
    
    Write-Host "📤 Uploading backend code to server..." -ForegroundColor Blue
    Write-Host "⚠️  This will overwrite files on the server!" -ForegroundColor Yellow
    
    $confirmation = Read-Host "Continue? (yes/no)"
    if ($confirmation -ne "yes") {
        Write-Host "Cancelled."
        return $false
    }
    
    $backendDir = $PSScriptRoot
    
    Write-Host "Uploading from: $backendDir"
    Write-Host "To: root@${IP}:/home/deploy/QHacks2026/backend/"
    
    try {
        scp -r $backendDir root@${IP}:/home/deploy/QHacks2026/
        Write-Host "✅ Upload complete!" -ForegroundColor Green
        Write-Host ""
        Write-Host "Next steps:"
        Write-Host "1. SSH into server: ssh root@$IP"
        Write-Host "2. Restart backend: sudo systemctl restart crm-backend"
    }
    catch {
        Write-Host "❌ Upload failed: $_" -ForegroundColor Red
        return $false
    }
}

# Main script logic
if ($Action -eq "help" -or $ServerIP -eq "") {
    Show-Help
    exit 0
}

Write-Host "CRM Backend Deployment Helper" -ForegroundColor Cyan
Write-Host "Server IP: $ServerIP" -ForegroundColor Cyan
Write-Host ""

switch ($Action) {
    "test" {
        Test-Backend -IP $ServerIP
    }
    "setup-env" {
        Setup-FrontendEnv -IP $ServerIP
    }
    "upload-code" {
        Upload-Code -IP $ServerIP
    }
    default {
        Show-Help
    }
}
